name: gsms-invest
channels:
  - conda-forge
dependencies:
  - python=3.10
  - natcap.invest=3.19.0
  - fastapi=0.136.3
  - uvicorn
  - python-multipart
  - aiofiles
  - rasterio=1.4.3
  - geopandas
  - pillow
  - numpy
  - sqlalchemy>=2.0
  - geoalchemy2
  - psycopg2
  - alembic
  - cryptography
